#!/bin/bash

# Change to WORKPLACE directory
cd "$WORKPLACE" || { echo "Failed to change directory to $WORKPLACE. Exiting."; exit 1; }

# Find distro folder
DISTRO_FOLDER=$(find "$WORKPLACE" -type d -name "distro")

# Parse the image-patch.ipp.yml to get distro
IMAGE_PATCH=$(find "$(pwd)" -name "image-patch.ipp.yml")

# Get the distro from the image-patch.ipp.yml
DISTRO=$(python3 parser.py "$IMAGE_PATCH")

# Ensure parser.py executed successfully
if [ $? -ne 0 ]; then
    echo "Failed to parse image patch file. Exiting."
    exit 1
fi

# Find the distro's yml
DISTRO=$(find "$DISTRO_FOLDER" -name "${DISTRO}.ipp.yml")

# Ensure distro yml exists
if [ -z "$DISTRO" ]; then
    echo "${DISTRO}.ipp.yml not found in $DISTRO_FOLDER. Exiting."
    exit 1
fi

CUSTOM="$DISTRO_FOLDER/custom.ipp.yml"

# Remove existing custom yml if it exists
if [ -e "$CUSTOM" ]; then
    rm -rf "$CUSTOM"
fi

# Create an empty custom yml file
touch "$CUSTOM"

# Apply the patch to the distro to create custom yml
python3 apply-patch.py "$DISTRO" "$IMAGE_PATCH" -o "$CUSTOM"

# Ensure apply-patch.py executed successfully
if [ $? -ne 0 ]; then
    echo "Failed to apply patch. Exiting."
    exit 1
fi

echo "The apply is completed"
sleep 3

# Change to osbuild-manifests directory
OSBUILD_MANIFESTS_DIR=$(find "$WORKPLACE" -type d -name "osbuild-manifests")
cd "$OSBUILD_MANIFESTS_DIR" || { echo "Failed to change directory to osbuild-manifests. Exiting."; exit 1; }

echo "Start the build custom image for qemu-arm64"

# Execute make command
make custom-qemu-developer-regular.aarch64.qcow2

# Ensure make command executed successfully
if [ $? -ne 0 ]; then
    echo "Failed to build custom image. Exiting."
    exit 1
fi
