#!/bin/bash

cd $WORKPLACE

# Clone the sample-images repository with submodules
git clone --recurse-submodule https://gitlab.com/CentOS/automotive/sample-images.git 

git clone https://github.com/DuyTongDuc2k/custom-sample.git

ls  -1

cd

