#!/bin/bash

dnf update -y

dnf install jq -y # for 

dnf install 'dnf-command(copr)' -y

dnf copr enable @osbuild/osbuild-stable -y
dnf copr enable @centos-automotive-sig/osbuild-auto -y

echo "==================================================="
echo "= Enable required COPR repositories is completed! ="
echo "==================================================="

# install modules for python
dnf install python3-pip -y

pip3 install pyyaml

pip3 install ruamel.yaml

pip3 install yq


# Install required packages
dnf install osbuild -y 
dnf install osbuild-auto -y
dnf install osbuild-ostree -y
dnf install osbuild-tools -y


